backend:
  name: git-gateway
  branch: main
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "src/content/posts/images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Categories", name: "categories", widget: "select", options: ['A', 'B', 'C', 'D', 'E'], multiple: true}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured", name: "featured", widget: "select", options: ['Featured? YES', 'Featured? NO']}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      # - { label: 'Content', name: 'content', widget: 'markdown' }
